USE [MCB_BANK]
GO

/****** Object:  Table [dbo].[INVOICE_DETAILS]    Script Date: 18-01-2021 05:46:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INVOICE_DETAILS](
	[INVOICE_ID] [int] IDENTITY(1,1) NOT NULL,
	[INVOICE_NUMBER] [varchar](250) NOT NULL,
	[INVOICE_DESCRIPTION] [varchar](1000) NULL,
	[INVOICE_DATE] [date] NULL,
	[INVOICE_AMOUNT] [decimal](18, 3) NULL,
	[INVOICE_STATUS] [varchar](50) NOT NULL,
	[INVOICE_HOLD_REASON] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[INVOICE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


