USE [MCB_BANK]
GO

/****** Object:  Table [dbo].[SUPPLIER_DETAILS]    Script Date: 18-01-2021 05:49:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SUPPLIER_DETAILS](
	[SUPPLIER_ID] [int] IDENTITY(1,1) NOT NULL,
	[SUPPLIER_NAME] [varchar](250) NOT NULL,
	[SUPP_CONTACT_NAME] [varchar](250) NOT NULL,
	[SUPP_CONTACT_NUMBER1] [int] NOT NULL,
	[SUPP_CONTACT_NUMBER2] [int] NOT NULL,
	[SUPP_EMAIL] [varchar](50) NOT NULL,
	[SUPP_ADDRESS] [varchar](1000) NOT NULL,
	[SUPP_ORDER_NUM] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[SUPPLIER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SUPPLIER_DETAILS] ADD  DEFAULT ((0)) FOR [SUPP_CONTACT_NUMBER1]
GO

ALTER TABLE [dbo].[SUPPLIER_DETAILS] ADD  DEFAULT ((0)) FOR [SUPP_CONTACT_NUMBER2]
GO


