-- =============================================
-- Author:		<SACHIN SHINDE>
-- Create date: <17-01-2021,,>
-- Description:	<GetSupplierOrderDetails>
-- =============================================
CREATE PROCEDURE usp_GetSupplierOrderDetails	

AS
BEGIN
	 SELECT 
	  (S.SUPPLIER_NAME) AS SUPPLIER_NAME,
	  S.SUPP_CONTACT_NAME
	,(SUBSTRING(cast(SUPP_CONTACT_NUMBER1 as varchar(10)),1,4)+'-'+SUBSTRING(cast(SUPP_CONTACT_NUMBER1 as varchar(10)),4,4)+'-'
		+SUBSTRING(cast(SUPP_CONTACT_NUMBER1 as varchar(10)),7,4)) AS SUPP_CONTACT_NUMBER1
		,(SUBSTRING(cast(SUPP_CONTACT_NUMBER2 as varchar(10)),1,4)+'-'+SUBSTRING(cast(SUPP_CONTACT_NUMBER2 as varchar(10)),4,4)+'-'
		+SUBSTRING(cast(SUPP_CONTACT_NUMBER2 as varchar(10)),7,4)) AS SUPP_CONTACT_NUMBER2
	,COUNT(O.ORDER_NUMBER) AS TOTAL_ORDERS
	,REPLACE(CONVERT(VARCHAR,CAST(SUM(O.ORDER_LINE_AMOUNT) AS MONEY),1), '.00','') AS ORDER_TOTAL_AMOUNT
	
    FROM  ORDER_DETAILS  O WITH (NOLOCK) LEFT OUTER JOIN SUPPLIER_DETAILS S WITH (NOLOCK) ON O.ORDER_SUPPLIER_ID=S.SUPPLIER_ID
	WHERE O.INVOICE_REFERENCE IS NOT NULL GROUP BY S.SUPPLIER_NAME,S.SUPP_CONTACT_NAME,S.SUPP_CONTACT_NUMBER1,S.SUPP_CONTACT_NUMBER2

END
GO
