
-- =============================================
-- Author:		<SACHIN SHINDE>
-- Create date: <17-01-2021,,>
-- Description:	<usp_GetThirdHighesOrderDetails>
-- =============================================
CREATE PROCEDURE usp_GetThirdHighesOrderDetails	

AS
BEGIN
		CREATE TABLE #ORDER_DETAILS
		(
		 ORDER_REFERENCE VARCHAR(250) NULL,
		 ORDER_DATE VARCHAR(18) NULL,
		 SUPPLIER_NAME VARCHAR(100)NULL,
		 ORDER_TOTAL_AMOUNT VARCHAR(100)NULL,
		 ORDER_STATUS VARCHAR(100)NULL,
		 INVOICE_REFERENCE VARCHAR(100)NULL
		);

		WITH CTE AS
		(
			  SELECT 
			  O.ORDER_NUMBER AS ORDER_REFERENCE
			 ,CAST(((DATENAME(month,O.ORDER_DATE)) + ' ' + (DATENAME(DAY,O.ORDER_DATE)) + ', ' + (DATENAME(YEAR,O.ORDER_DATE))) AS VARCHAR(16)) AS ORDER_DATE
			,UPPER(S.SUPPLIER_NAME) AS SUPPLIER_NAME
			,REPLACE(CONVERT(VARCHAR,CAST(SUM(O.ORDER_LINE_AMOUNT) AS MONEY),1), '.00','') AS ORDER_TOTAL_AMOUNT
			,O.ORDER_STATUS,O.INVOICE_REFERENCE,
			ROW_NUMBER() OVER(ORDER BY SUM(O.ORDER_LINE_AMOUNT) DESC) AS 'RowNum'
			FROM ORDER_DETAILS O with (nolock) LEFT OUTER JOIN SUPPLIER_DETAILS S with (nolock) ON O.ORDER_SUPPLIER_ID=S.SUPPLIER_ID
			WHERE O.INVOICE_REFERENCE IS NOT NULL GROUP BY O.ORDER_DATE,O.ORDER_STATUS
			,S.SUPPLIER_NAME,O.ORDER_NUMBER,O.INVOICE_REFERENCE

		)

	INSERT INTO #ORDER_DETAILS (ORDER_REFERENCE,ORDER_DATE,SUPPLIER_NAME,ORDER_TOTAL_AMOUNT,ORDER_STATUS,INVOICE_REFERENCE)
	SELECT C.ORDER_REFERENCE,C.ORDER_DATE,C.SUPPLIER_NAME,C.ORDER_TOTAL_AMOUNT,C.ORDER_STATUS,C.INVOICE_REFERENCE FROM CTE C WHERE RowNum = 3

	DECLARE @INVOICE_REFERENCE VARCHAR(1000)

	SET @INVOICE_REFERENCE  = ( SELECT STUFF((SELECT ',' + INVOICE_REFERENCE
				FROM INVOICE_DETAILS I with (nolock) LEFT OUTER JOIN ORDER_DETAILS O with (nolock) ON
				I.INVOICE_NUMBER = O.INVOICE_REFERENCE WHERE O.ORDER_NUMBER  = (SELECT ORDER_REFERENCE FROM #ORDER_DETAILS)
				FOR XML PATH('')) ,1,1,'') AS INVOICE_REFERENCE )

	SELECT STUFF(ORDER_REFERENCE, 1, 4, '') AS ORDER_REFERENCE,ORDER_DATE,SUPPLIER_NAME,ORDER_TOTAL_AMOUNT,ORDER_STATUS,INVOICE_REFERENCE
	,@INVOICE_REFERENCE AS INVOICE_REFERENCE  FROM #ORDER_DETAILS


	DROP TABLE #ORDER_DETAILS

END
GO




