
-- =============================================
-- Author:		<SACHIN SHINDE>
-- Create date: <17-01-2021,,>
-- Description:	<usp_GetDistinctInvoiceDetails>
-- =============================================
CREATE PROCEDURE usp_GetDistinctInvoiceDetails	

AS
BEGIN
		 
	  CREATE TABLE #InviceOrderDetails
	  (  
		 INVOICE_REFERENCE varchar(250) NULL,
		 ORDER_PERIOD VARCHAR(20) NULL,
		 ORDER_TOTAL_AMOUNT VARCHAR(250) NULL,
		 ORDER_STATUS VARCHAR(250) NULL,
		 SUPPLIER_NAME VARCHAR(250) NULL,
		 INVOICE_TOTAL_AMOUNT VARCHAR(250) NULL,

	  )
		INSERT INTO #InviceOrderDetails (INVOICE_REFERENCE,ORDER_PERIOD,ORDER_TOTAL_AMOUNT,ORDER_STATUS,SUPPLIER_NAME
		,INVOICE_TOTAL_AMOUNT)
		SELECT  DISTINCT O.INVOICE_REFERENCE AS INVOICE_NUMBER
		,REPLACE(RIGHT(CONVERT(VARCHAR(9),O.ORDER_DATE,6),6),' ', '-') AS ORDER_PERIOD
		,REPLACE(CONVERT(VARCHAR,CAST(SUM(O.ORDER_LINE_AMOUNT) AS MONEY),1), '.00','') AS ORDER_TOTAL_AMOUNT
		,O.ORDER_STATUS
		,UPPER(LEFT(S.SUPPLIER_NAME,1))+LOWER(SUBSTRING(S.SUPPLIER_NAME,2,LEN(S.SUPPLIER_NAME))) AS SUPPLIER_NAME
		,REPLACE(CONVERT(VARCHAR,CAST(SUM(I.INVOICE_AMOUNT) AS MONEY),1), '.00','') AS INVOICE_TOTAL_AMOUNT
		FROM ORDER_DETAILS O (nolock) LEFT OUTER JOIN SUPPLIER_DETAILS S (nolock) ON O.ORDER_SUPPLIER_ID=S.SUPPLIER_ID
		LEFT OUTER JOIN INVOICE_DETAILS I with (nolock) ON O.INVOICE_REFERENCE = I.INVOICE_NUMBER
		WHERE O.INVOICE_REFERENCE IS NOT NULL GROUP BY O.INVOICE_REFERENCE,O.ORDER_DATE,O.ORDER_STATUS
		,S.SUPPLIER_NAME;


		WITH CTE AS
		(   SELECT InvoiceOrderDetails.INVOICE_REFERENCE,InvoiceOrderDetails.ORDER_PERIOD,InvoiceOrderDetails.ORDER_TOTAL_AMOUNT,
			InvoiceOrderDetails.ORDER_STATUS,InvoiceOrderDetails.SUPPLIER_NAME,
			InvoiceOrderDetails.INVOICE_TOTAL_AMOUNT,O.ORDER_NUMBER,
			CASE 
				  WHEN I.INVOICE_STATUS = 'Paid' THEN 'OK'
				  WHEN I.INVOICE_STATUS = 'Pending' THEN 'To follow up'
				  WHEN ISNULL(I.INVOICE_STATUS,'') = '' THEN 'To verify'
					END AS [ACTION],
				ROW_NUMBER() OVER (PARTITION BY InvoiceOrderDetails.INVOICE_REFERENCE ORDER BY InvoiceOrderDetails.INVOICE_REFERENCE DESC) AS rn
			FROM #InviceOrderDetails InvoiceOrderDetails LEFT OUTER JOIN INVOICE_DETAILS I ON InvoiceOrderDetails.INVOICE_REFERENCE
			= I.INVOICE_NUMBER
			LEFT OUTER JOIN ORDER_DETAILS O (nolock) ON I.INVOICE_NUMBER = O.INVOICE_REFERENCE
		)

		SELECT STUFF(ORDER_NUMBER, 1, 4, '') AS ORDER_REFERENCE,ORDER_NUMBER,INVOICE_REFERENCE,ORDER_PERIOD,ORDER_TOTAL_AMOUNT,ORDER_STATUS,SUPPLIER_NAME
			,INVOICE_TOTAL_AMOUNT,[ACTION] FROM cte C
		WHERE rn = 1

		DROP TABLE #InviceOrderDetails

END
GO




